# Generated by Django 4.2.6 on 2024-05-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='Cart',
        ),
    ]
