# Generated by Django 4.2.6 on 2024-05-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_wishlist_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobilenumber',
            field=models.CharField(default=9000, max_length=15),
        ),
    ]
