# Generated by Django 4.2.6 on 2024-06-05 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_comment_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='product',
        ),
        migrations.AddField(
            model_name='categories',
            name='name',
            field=models.CharField(default='pots', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categories'),
        ),
    ]
