# Generated by Django 4.2.6 on 2024-06-19 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_categories_product_categories_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.cart'),
        ),
    ]
