# Generated by Django 4.2.6 on 2024-06-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_order_remove_address_product_orderitem_order_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='d_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='o_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
